server:
  port: 1404
spring:
  profiles:
    active: kfd
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:4444/schooldb
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: kfd


